export const categories = [
  { name: 'Italiana' },
  { name: 'Mexicana' },
  { name: 'Japonesa' },
  { name: 'China' },
  { name: 'Americana' },
  { name: 'Mediterránea' },
  { name: 'India' },
  { name: 'Española' },
  { name: 'Vegetariana/Vegana' },
  { name: 'Rápida (Fast Food)' },
  { name: 'Pizzería' },
  { name: 'Cafetería' },
  { name: 'Buffet' },
  { name: 'Francesa' },
  { name: 'Barbacoa' },
  { name: 'Peruana' },
  { name: 'Gourmet' },
  { name: 'Fusión' },
  { name: 'Postres' },
  { name: 'Otros' },
];
