export const cities = [
  { name: 'Buenos Aires' },
  { name: 'Córdoba' },
  { name: 'Rosario' },
  { name: 'Mendoza' },
  { name: 'La Plata' },
  { name: 'Mar del Plata' },
  { name: 'Tucumán' },
  { name: 'Salta' },
  { name: 'Santa Fe' },
  { name: 'Bahía Blanca' },
  { name: 'Neuquén' },
  { name: 'San Juan' },
  { name: 'Río Cuarto' },
  { name: 'Santiago del Estero' },
  { name: 'Posadas' },
  { name: 'Resistencia' },
  { name: 'San Luis' },
  { name: 'Corrientes' },
  { name: 'Ushuaia' },
  { name: 'Trelew' },
];
