### Consular todos los restaurantes
GET http://localhost:3000/api/restaurantes
Content-Type: application/json

### Crear un nuevo restaurante
POST http://localhost:3000/api/restaurantes
Content-Type: application/json

{
  "name": "Restaurante3 Prueba",
  "ubicacion": "Calle Falsa 456",
  "telefono": "123456789"
}
### Consular un restaurante por ID:
GET http://localhost:3000/api/restaurantes/1
Content-Type: application/json

### actualizar restaurante por ID:
PUT http://localhost:3000/api/restaurantes/1
Content-Type: application/json

{
  "name": "Nuevo Nombre",
  "ubicacion": "Nueva Ubicación",
  "telefono": "987654321"
}

### Eliminar restaurante por ID:
DELETE http://localhost:3000/api/restaurantes/1
Content-Type: application/json



