### Obtener CSRF token
GET http://localhost:3000/api/auth/csrf

### Login con CSRF token
POST http://localhost:3000/api/auth/callback/credentials
Content-Type: application/x-www-form-urlencoded

csrfToken=be1dbfc5031c91756123bb8ac821fbb9f0c8b6b9d2c52d1024c84d4a985d8f74&email=test@test.com&password=123


### Crear una nueva reseña
POST http://localhost:3000/api/reviews
Content-Type: application/json

{
  "comment": "Restaurante1 user1",
  "rating": 5,
  "restaurantId": 1,
  "userId": 1
}

### Obtener todas las reseñas
GET http://localhost:3000/api/reviews

### Consultar una reseña por ID
GET http://localhost:3000/api/reviews/1

### Actualizar una reseña por ID
PUT http://localhost:3000/api/reviews/1
Content-Type: application/json

{
  "comment": "Actualizacion del comentario"
}

### Actualizar una reseña por ID
PUT http://localhost:3000/api/reviews/14
Content-Type: application/json

{
  "rating": 1
}

### Eliminar una reseña por ID
DELETE http://localhost:3000/api/reviews/9

### Obtener todas las reseñas del restaurante
GET http://localhost:3000/api/reviews/restaurante/1

### Obtener todas las reseñas del usuario
GET http://localhost:3000/api/reviews/usuario/2
