### GET request
GET http://localhost:3000/api/hello
Content-Type: application/json


### Crear un nuevo usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "user 1",
    "email": "user1@test.com",
    "password": "123"
}

### Obtener CSRF token
GET http://localhost:3000/api/auth/csrf


### Login con CSRF token
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
  "csrfToken": "8190380692d25feb093b4d2e5cc73ef5c27f791638a69a81527aea885357127b",
  "email": "test@test.com",
  "password": "123"
}



### Actualizar el perfil del usuario
PATCH http://localhost:3000/api/user/profile
Content-Type: application/json

{
  "name": "John",
  "lastname": "Doe",
  "birthDate": "1990-01-01",
  "avatarUrl": "http://example.com/avatar.jpg"
}